services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: attendance_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  db-data:
